noter:
  interface: cli
  output: csv

note_types:
  - type: question
    command: q
  - type: bug
    command: b
  - type: issue
    command: i
  - type: setup
    command: s
  - type: note
    command: n

post_session:
  task_breakdown:
    - setup
    - testing
    - investigating
